/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address { 'zip' : string, 'street' : string, 'city' : string }
export type Department = { 'emergency' : null } |
  { 'cardiology' : null } |
  { 'generalMedicine' : null } |
  { 'orthopedics' : null } |
  { 'pediatrics' : null } |
  { 'neurology' : null };
export interface EmergencyData {
  'id' : string,
  'patientId' : string,
  'description' : string,
  'department' : Department,
}
export interface Patient { 'id' : string, 'name' : string, 'address' : Address }
export interface PersistentCaseAssignment {
  'doctorId' : string,
  'caseId' : string,
}
export interface PersistentDoctor {
  'id' : string,
  'name' : string,
  'department' : Department,
}
export interface PersistentEmergency {
  'id' : string,
  'status' : string,
  'patientId' : string,
  'description' : string,
  'department' : Department,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPatient' : ActorMethod<[Patient], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCaseToDoctor' : ActorMethod<[string, string], undefined>,
  'createEmergency' : ActorMethod<[EmergencyData], undefined>,
  'departmentTransfer' : ActorMethod<[string, Department], undefined>,
  'getAllEmergencies' : ActorMethod<[], Array<PersistentEmergency>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseAssignmentsForDoctor' : ActorMethod<
    [string],
    Array<PersistentCaseAssignment>
  >,
  'getDoctorsByDepartment' : ActorMethod<[Department], Array<PersistentDoctor>>,
  'getEmergenciesByDepartment' : ActorMethod<
    [Department],
    Array<PersistentEmergency>
  >,
  'getPatient' : ActorMethod<[string], Patient>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];