/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Department = IDL.Variant({
  'emergency' : IDL.Null,
  'cardiology' : IDL.Null,
  'generalMedicine' : IDL.Null,
  'orthopedics' : IDL.Null,
  'pediatrics' : IDL.Null,
  'neurology' : IDL.Null,
});
export const DoctorData = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'department' : Department,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
});
export const Patient = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'address' : Address,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmergencyData = IDL.Record({
  'id' : IDL.Text,
  'patientId' : IDL.Text,
  'description' : IDL.Text,
  'department' : Department,
});
export const PersistentEmergency = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'patientId' : IDL.Text,
  'description' : IDL.Text,
  'department' : Department,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const PersistentCaseAssignment = IDL.Record({
  'doctorId' : IDL.Text,
  'caseId' : IDL.Text,
});
export const PersistentDoctor = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'department' : Department,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDoctor' : IDL.Func([DoctorData], [], []),
  'addPatient' : IDL.Func([Patient], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCaseToDoctor' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createEmergency' : IDL.Func([EmergencyData], [], []),
  'departmentTransfer' : IDL.Func([IDL.Text, Department], [], []),
  'getAllEmergencies' : IDL.Func([], [IDL.Vec(PersistentEmergency)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseAssignmentsForDoctor' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PersistentCaseAssignment)],
      ['query'],
    ),
  'getDoctorsByDepartment' : IDL.Func(
      [Department],
      [IDL.Vec(PersistentDoctor)],
      ['query'],
    ),
  'getEmergenciesByDepartment' : IDL.Func(
      [Department],
      [IDL.Vec(PersistentEmergency)],
      ['query'],
    ),
  'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Department = IDL.Variant({
    'emergency' : IDL.Null,
    'cardiology' : IDL.Null,
    'generalMedicine' : IDL.Null,
    'orthopedics' : IDL.Null,
    'pediatrics' : IDL.Null,
    'neurology' : IDL.Null,
  });
  const DoctorData = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'department' : Department,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
  });
  const Patient = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'address' : Address,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmergencyData = IDL.Record({
    'id' : IDL.Text,
    'patientId' : IDL.Text,
    'description' : IDL.Text,
    'department' : Department,
  });
  const PersistentEmergency = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'patientId' : IDL.Text,
    'description' : IDL.Text,
    'department' : Department,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const PersistentCaseAssignment = IDL.Record({
    'doctorId' : IDL.Text,
    'caseId' : IDL.Text,
  });
  const PersistentDoctor = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'department' : Department,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDoctor' : IDL.Func([DoctorData], [], []),
    'addPatient' : IDL.Func([Patient], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCaseToDoctor' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createEmergency' : IDL.Func([EmergencyData], [], []),
    'departmentTransfer' : IDL.Func([IDL.Text, Department], [], []),
    'getAllEmergencies' : IDL.Func(
        [],
        [IDL.Vec(PersistentEmergency)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseAssignmentsForDoctor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PersistentCaseAssignment)],
        ['query'],
      ),
    'getDoctorsByDepartment' : IDL.Func(
        [Department],
        [IDL.Vec(PersistentDoctor)],
        ['query'],
      ),
    'getEmergenciesByDepartment' : IDL.Func(
        [Department],
        [IDL.Vec(PersistentEmergency)],
        ['query'],
      ),
    'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };