/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CaseStatus = { 'resolved' : null } |
  { 'assigned' : null } |
  { 'open' : null };
export type Department = { 'emergency' : null } |
  { 'cardiology' : null } |
  { 'generalMedicine' : null } |
  { 'orthopedics' : null } |
  { 'pediatrics' : null } |
  { 'neurology' : null };
export interface Doctor {
  'id' : bigint,
  'name' : string,
  'available' : boolean,
  'registrationCode' : string,
  'department' : Department,
}
export interface EmergencyCase {
  'id' : bigint,
  'status' : CaseStatus,
  'createdAt' : bigint,
  'assignedDoctorId' : [] | [bigint],
  'patientName' : string,
  'severity' : Severity,
  'condition' : string,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateDoctor' : ActorMethod<[bigint], Doctor>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateDoctor' : ActorMethod<[bigint], Doctor>,
  'doctorLogin' : ActorMethod<[string, Department], Doctor>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllDoctorsPublic' : ActorMethod<[], Array<Doctor>>,
  'getAllEmergencyCases' : ActorMethod<[], Array<EmergencyCase>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerDoctor' : ActorMethod<[string, Department, string], Doctor>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleDoctorAvailability' : ActorMethod<[bigint], Doctor>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];