/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Department = IDL.Variant({
  'emergency' : IDL.Null,
  'cardiology' : IDL.Null,
  'generalMedicine' : IDL.Null,
  'orthopedics' : IDL.Null,
  'pediatrics' : IDL.Null,
  'neurology' : IDL.Null,
});
export const Doctor = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'registrationCode' : IDL.Text,
  'department' : Department,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CaseStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'assigned' : IDL.Null,
  'open' : IDL.Null,
});
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const EmergencyCase = IDL.Record({
  'id' : IDL.Nat,
  'status' : CaseStatus,
  'createdAt' : IDL.Int,
  'assignedDoctorId' : IDL.Opt(IDL.Nat),
  'patientName' : IDL.Text,
  'severity' : Severity,
  'condition' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateDoctor' : IDL.Func([IDL.Nat], [Doctor], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateDoctor' : IDL.Func([IDL.Nat], [Doctor], []),
  'doctorLogin' : IDL.Func([IDL.Text, Department], [Doctor], ['query']),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllDoctorsPublic' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllEmergencyCases' : IDL.Func([], [IDL.Vec(EmergencyCase)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerDoctor' : IDL.Func([IDL.Text, Department, IDL.Text], [Doctor], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleDoctorAvailability' : IDL.Func([IDL.Nat], [Doctor], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Department = IDL.Variant({
    'emergency' : IDL.Null,
    'cardiology' : IDL.Null,
    'generalMedicine' : IDL.Null,
    'orthopedics' : IDL.Null,
    'pediatrics' : IDL.Null,
    'neurology' : IDL.Null,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'registrationCode' : IDL.Text,
    'department' : Department,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CaseStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'assigned' : IDL.Null,
    'open' : IDL.Null,
  });
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const EmergencyCase = IDL.Record({
    'id' : IDL.Nat,
    'status' : CaseStatus,
    'createdAt' : IDL.Int,
    'assignedDoctorId' : IDL.Opt(IDL.Nat),
    'patientName' : IDL.Text,
    'severity' : Severity,
    'condition' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateDoctor' : IDL.Func([IDL.Nat], [Doctor], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateDoctor' : IDL.Func([IDL.Nat], [Doctor], []),
    'doctorLogin' : IDL.Func([IDL.Text, Department], [Doctor], ['query']),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllDoctorsPublic' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllEmergencyCases' : IDL.Func([], [IDL.Vec(EmergencyCase)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerDoctor' : IDL.Func([IDL.Text, Department, IDL.Text], [Doctor], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleDoctorAvailability' : IDL.Func([IDL.Nat], [Doctor], []),
  });
};

export const init = ({ IDL }) => { return []; };