/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CaseStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'assigned' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export type Department = { 'emergency' : null } |
  { 'cardiology' : null } |
  { 'generalMedicine' : null } |
  { 'orthopedics' : null } |
  { 'pediatrics' : null } |
  { 'neurology' : null };
export interface Doctor {
  'id' : bigint,
  'status' : DoctorStatus,
  'yearsOfExperience' : [] | [bigint],
  'contactInfo' : string,
  'name' : string,
  'available' : boolean,
  'registrationCode' : string,
  'registrationDate' : bigint,
  'department' : Department,
  'certifications' : [] | [Array<string>],
}
export type DoctorLoginResult = { 'success' : Doctor } |
  { 'notApproved' : null } |
  { 'doctorNotFound' : null } |
  { 'invalidCredentials' : null };
export type DoctorStatus = { 'pendingApproval' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface EmergencyCase {
  'id' : bigint,
  'status' : CaseStatus,
  'patientDetails' : string,
  'caseType' : Department,
  'assignedDoctorId' : [] | [bigint],
  'submissionDate' : bigint,
  'patientName' : string,
  'severity' : Severity,
  'condition' : string,
}
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveDoctor' : ActorMethod<[bigint], Doctor>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDoctorToCase' : ActorMethod<[bigint, bigint], EmergencyCase>,
  'deleteCase' : ActorMethod<[bigint], undefined>,
  'doctorLogin' : ActorMethod<[bigint, string], DoctorLoginResult>,
  'getActiveCriticalEmergencyCounts' : ActorMethod<
    [],
    { 'totalOpen' : bigint, 'totalActive' : bigint, 'totalCritical' : bigint }
  >,
  'getAllCasesPublic' : ActorMethod<[], Array<EmergencyCase>>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllDoctorsPublic' : ActorMethod<[], Array<Doctor>>,
  'getAllEmergencyCases' : ActorMethod<[], Array<EmergencyCase>>,
  'getAvailableDoctorsByDepartment' : ActorMethod<[Department], Array<Doctor>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingApprovalDoctors' : ActorMethod<[], Array<Doctor>>,
  'getTotalEmergencyCaseCount' : ActorMethod<[], bigint>,
  'getTotalRegisteredDoctorCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerDoctor' : ActorMethod<
    [string, Department, string, string, [] | [bigint], [] | [Array<string>]],
    Doctor
  >,
  'rejectDoctor' : ActorMethod<[bigint], Doctor>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCase' : ActorMethod<
    [string, string, string, Department, Severity],
    EmergencyCase
  >,
  'updateCaseStatus' : ActorMethod<[bigint, CaseStatus], EmergencyCase>,
  'updateDoctorAvailability' : ActorMethod<[bigint, boolean], undefined>,
  'updateDoctorDepartment' : ActorMethod<[bigint, Department], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];